---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules

env:
  matrix:
    - EMBER_CHANNEL=release
    - EMBER_CHANNEL=beta
    - EMBER_CHANNEL=canary

matrix:
  allow_failures:
    - env: EMBER_CHANNEL=beta
    - env: EMBER_CHANNEL=canary

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test

after_success:
  - ./scripts/travis/after-success.sh

notifications:
  slack:
    secure: fQL4QI4wBqU6Vjh2qmyzDMT+WV4o0QBxljGEC3hGsPONR9RVfrxCQ8HioRmN6bUMyV/9MP9d6lnOqAUMulfc14QN6Yck8SgxUlusv7cGmeOuhUeTRsd9KJyxtmYP/fwPd7V/m2JstLkMDg3LGtU0EcnIEKklnRTEe7YSP9+4KoQ=
